# Generated by Django 5.0.3 on 2026-04-27 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('type', models.CharField(choices=[('CREDIT_RECHARGE', 'Credit Recharge'), ('DEBIT_TICKET', 'Debit Ticket'), ('REFUND_DISPUTE', 'Refund Dispute'), ('DEBIT_FINE', 'Debit Fine')], max_length=20)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('payment_gateway_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='wallet_payments.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
    ]
