# Generated by Django 5.0.3 on 2026-04-27 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_paid', models.DecimalField(decimal_places=3, max_digits=12)),
                ('zone_validity', models.CharField(max_length=50)),
                ('cryptographic_signature', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('USED', 'Used'), ('FRAUDULENT', 'Fraudulent')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_location_lat', models.FloatField(blank=True, null=True)),
                ('scan_location_lng', models.FloatField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField()),
                ('is_cryptographically_valid', models.BooleanField()),
                ('sync_status', models.CharField(default='PENDING_SYNC', max_length=20)),
                ('device_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticketing_validation.ticket')),
            ],
            options={
                'db_table': 'validation_logs',
            },
        ),
    ]
