# Generated by Django 5.0.3 on 2026-04-27 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_cin', models.CharField(max_length=20)),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.TextField()),
                ('infraction_location_lat', models.FloatField(blank=True, null=True)),
                ('infraction_location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('UNPAID_PENALTY', 'Unpaid Penalty'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=20)),
                ('proof_photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fines',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('proof_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED_REJECTED', 'Resolved Rejected'), ('RESOLVED_ACCEPTED', 'Resolved Accepted')], default='OPEN', max_length=25)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fines_disputes.fine')),
            ],
            options={
                'db_table': 'disputes',
            },
        ),
    ]
